//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Comments = new HashSet<Comments>();
            this.Posts = new HashSet<Posts>();
            this.Posts1 = new HashSet<Posts>();
            this.Posts2 = new HashSet<Posts>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<Posts> Posts { get; set; }
        public virtual ICollection<Posts> Posts1 { get; set; }
        public virtual ICollection<Posts> Posts2 { get; set; }
    }
}
